pipeline {
  agent {
    kubernetes {
      yaml """
        apiVersion: v1
        kind: Pod
        metadata:
          labels:
            agent: docker
        spec:
          containers:
          - name: docker
            image: docker:latest
            command:
            - cat
            tty: true
          - name: buildkit
            image: moby/buildkit:v0.8.1
            env:
            - name: BUILDKIT_HOST
              value: tcp://buildkitd:1234
            command:
            - cat
            tty: true
          volumes:
          - name: docker-socket
            hostPath:
              path: /var/run/docker.sock
          - name: buildkitd
            emptyDir: {}
      """
    }
  }

  stages {
    stage('Checkout') {
      steps {
        git branch: 'master', url: 'https://github.com/mckafeh/docker.git', dir: 'jenkins-buildkit'
      }
    }
    
    stage('Build') {
      steps {
        container('docker') {
          sh 'docker buildx create --use'
          
          // Add any necessary build steps here
          sh 'docker buildx build --progress=plain --builder buildkit --tag my-image:latest -f Jenkinsfile-docker'
        }
      }
    }
 }
  }
}
